using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace OneLastClick.Services.SourceGenerator
{
    [Generator]
    public class InjectServicesSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (OneLastClickServicesReferences.TryResolveReferences(context, out OneLastClickServicesReferences references) == false)
            {
                return;
            }

            List<INamedTypeSymbol> typesWithInjection = context.GetAllTypesWithMemberAttribute(references.InjectServiceAttributeSymbol);
            
            string compilationName = context.Compilation.AssemblyName ?? "<unknown>";
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDefinitions.ServicesWithInjectAttributesFoundDiagnostic, Location.None, typesWithInjection.Count, compilationName));
            
            foreach (INamedTypeSymbol type in typesWithInjection)
            {
                GenerateResolveMethod(context, references, type);
            }
        }
        
        private static void GenerateResolveMethod(GeneratorExecutionContext context, OneLastClickServicesReferences references, INamedTypeSymbol type)
        {
            List<ISymbol> injectableMembers = GetInjectableMembers(type, references.InjectServiceAttributeSymbol);

            if (injectableMembers.Count == 0)
            {
                return;
            }

            if (type.DeclaringSyntaxReferences.Length == 0)
            {
                return;
            }

            bool hasInjectableBase = HasInjectableBaseType(type, references.InjectServiceAttributeSymbol);

            string resolverTypeName = references.ServiceResolverInterfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string injectableTypeName = references.ServiceInjectableInterfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            StringBuilder source = new StringBuilder();

            source.AppendLine("// <auto-generated />");
            source.AppendLine("using OneLastClick.Services;");
            source.AppendLine();

            AppendNamespaceStart(source, type);
            AppendContainingTypesStart(source, type);
            
            source.Append("    public ");

            if (type.IsSealed)
            {
                source.Append("sealed ");
            }

            source.Append("partial class ");
            source.Append(type.Name);

            if (hasInjectableBase == false)
            {
                source.AppendLine();
                source.Append("        : ");
                source.Append(injectableTypeName);
            }

            source.AppendLine();
            source.AppendLine("    {");

            if (hasInjectableBase)
            {
                source.Append("        public override void InjectServices(");
            }
            else if (type.IsSealed)
            {
                source.Append("        public void InjectServices(");
            }
            else
            {
                source.Append("        public virtual void InjectServices(");
            }

            source.Append(resolverTypeName);
            source.AppendLine(" resolver)");
            source.AppendLine("        {");

            if (hasInjectableBase)
            {
                source.AppendLine("            base.InjectServices(resolver);");
            }

            foreach (ISymbol member in injectableMembers)
            {
                AppendMemberResolution(source, member);
            }

            source.AppendLine("        }");
            source.AppendLine("    }");

            AppendContainingTypesEnd(source, type);
            AppendNamespaceEnd(source, type);

            string hintName = GetHintName(type);

            context.AddSource(hintName, source.ToString());
        }
        
        private static void AppendContainingTypesStart(StringBuilder source, INamedTypeSymbol type)
        {
            var containingTypes = new Stack<INamedTypeSymbol>();

            for (var t = type.ContainingType; t != null; t = t.ContainingType)
                containingTypes.Push(t);

            foreach (var t in containingTypes)
            {
                source.Append("    public partial class ");
                source.Append(t.Name);
                source.AppendLine();
                source.AppendLine("    {");
            }
        }

        private static void AppendContainingTypesEnd(StringBuilder source, INamedTypeSymbol type)
        {
            for (var t = type.ContainingType; t != null; t = t.ContainingType)
            {
                source.AppendLine("    }");
            }
        }
        
        private static void AppendMemberResolution(StringBuilder source, ISymbol member)
        {
            string memberTypeName;

            if (member is IFieldSymbol field)
            {
                memberTypeName = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }
            else if (member is IPropertySymbol property)
            {
                memberTypeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }
            else
            {
                return;
            }

            source.Append("            ");
            source.Append(member.Name);
            source.Append(" = resolver.Get<");
            source.Append(memberTypeName);
            source.AppendLine(">();");
        }

        
        private static List<ISymbol> GetInjectableMembers(INamedTypeSymbol type, INamedTypeSymbol injectServiceAttributeSymbol)
        {
            var members = new List<ISymbol>();

            foreach (ISymbol member in type.GetMembers())
            {
                if (HasAttribute(member, injectServiceAttributeSymbol) == false)
                {
                    continue;
                }

                if (member is IFieldSymbol field)
                {
                    if (field.IsStatic)
                    {
                        // TODO: Add diagnostic error.
                        continue;
                    }

                    members.Add(field);
                }
                else if (member is IPropertySymbol property)
                {
                    if (property.IsStatic)
                    {
                        // TODO: Add diagnostic error.
                        continue;
                    }

                    if (property.SetMethod == null)
                    {
                        // TODO: Add diagnostic error if no set
                        continue;
                    }

                    members.Add(property);
                }
            }

            return members;
        }
        
        private static bool HasInjectableBaseType(INamedTypeSymbol type, INamedTypeSymbol injectServiceAttributeSymbol)
        {
            INamedTypeSymbol baseType = type.BaseType;

            while (baseType != null)
            {
                if (GetInjectableMembers(baseType, injectServiceAttributeSymbol).Count > 0)
                {
                    return true;
                }

                baseType = baseType.BaseType;
            }

            return false;
        }
        
        private static bool HasAttribute(ISymbol symbol, INamedTypeSymbol attributeSymbol)
        {
            foreach (AttributeData attribute in symbol.GetAttributes())
            {
                if (SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, attributeSymbol))
                {
                    return true;
                }
            }

            return false;
        }
        
        private static void AppendNamespaceStart(StringBuilder source, INamedTypeSymbol type)
        {
            string namespaceName = type.ContainingNamespace?.ToDisplayString();

            if (string.IsNullOrEmpty(namespaceName))
            {
                return;
            }

            source.Append("namespace ");
            source.Append(namespaceName);
            source.AppendLine();
            source.AppendLine("{");
        }

        private static void AppendNamespaceEnd(StringBuilder source, INamedTypeSymbol type)
        {
            string namespaceName = type.ContainingNamespace?.ToDisplayString();

            if (string.IsNullOrEmpty(namespaceName))
            {
                return;
            }

            source.AppendLine("}");
        }

        private static string GetHintName(INamedTypeSymbol type)
        {
            string name = type.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat);

            return name
                       .Replace("global::", string.Empty)
                       .Replace(".", "_")
                       .Replace("<", "_")
                       .Replace(">", "_")
                   + ".InjectService.g.cs";
        }
    }
}