using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace OneLastClick.Services.SourceGenerator
{
    [Generator]
    public class MonoBehaviourServiceSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (OneLastClickServicesReferences.TryResolveReferences(context, out OneLastClickServicesReferences references) == false)
            {
                return;
            }

            List<INamedTypeSymbol> monoBehaviourTypes = context.GetAllTypesWithAttribute(references.MonoBehaviourServiceAttributeSymbol);

            string compilationName = context.Compilation.AssemblyName ?? "<unknown>";
            context.ReportDiagnostic(
                Diagnostic.Create(
                    DiagnosticDefinitions.MonoBehaviourServicesFoundDiagnostic,
                    Location.None,
                    monoBehaviourTypes.Count,
                    compilationName));

            foreach (INamedTypeSymbol type in monoBehaviourTypes)
            {
                GenerateServiceRegisterer(context, references, type);
            }
        }

        private static void GenerateServiceRegisterer(
            GeneratorExecutionContext context,
            OneLastClickServicesReferences references,
            INamedTypeSymbol type)
        {
            if (type.DeclaringSyntaxReferences.Length == 0)
            {
                return;
            }

            List<ITypeSymbol> registerTypes = GetRegisterTypes(type, references.MonoBehaviourServiceAttributeSymbol);

            string registererInterface = references.ServiceRegistererInterfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string builderType = references.ServiceCollectionBuilderSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string selfType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var source = new StringBuilder();

            source.AppendLine("// <auto-generated />");
            source.AppendLine("using OneLastClick.Services;");
            source.AppendLine();

            AppendNamespaceStart(source, type);
            AppendContainingTypesStart(source, type);

            source.Append("    public ");

            if (type.IsSealed)
            {
                source.Append("sealed ");
            }

            source.Append("partial class ");
            source.Append(type.Name);
            source.AppendLine();
            source.Append("        : ");
            source.AppendLine(registererInterface);
            source.AppendLine("    {");

            source.Append("        public void RegisterServices(");
            source.Append(builderType);
            source.AppendLine(" servicesCollectionBuilder)");
            source.AppendLine("        {");

            if (registerTypes.Count == 0)
            {
                source.Append("            servicesCollectionBuilder.Register<");
                source.Append(selfType);
                source.AppendLine(">(this);");
            }
            else
            {
                foreach (ITypeSymbol registerType in registerTypes)
                {
                    source.Append("            servicesCollectionBuilder.Register<");
                    source.Append(registerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                    source.Append(", ");
                    source.Append(selfType);
                    source.AppendLine(">();");
                }
            }

            source.AppendLine("        }");
            source.AppendLine("    }");

            AppendContainingTypesEnd(source, type);
            AppendNamespaceEnd(source, type);

            context.AddSource(GetHintName(type), source.ToString());
        }

        private static List<ITypeSymbol> GetRegisterTypes(
            INamedTypeSymbol type,
            INamedTypeSymbol attributeSymbol)
        {
            var result = new List<ITypeSymbol>();

            foreach (AttributeData attribute in type.GetAttributes())
            {
                if (!SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, attributeSymbol))
                {
                    continue;
                }

                foreach (TypedConstant arg in attribute.ConstructorArguments)
                {
                    if (arg.Kind == TypedConstantKind.Array)
                    {
                        foreach (TypedConstant value in arg.Values)
                        {
                            if (value.Value is ITypeSymbol typeSymbol)
                            {
                                result.Add(typeSymbol);
                            }
                        }
                    }
                    else if (arg.Value is ITypeSymbol typeSymbol)
                    {
                        result.Add(typeSymbol);
                    }
                }

                break;
            }

            return result;
        }

        private static void AppendContainingTypesStart(StringBuilder source, INamedTypeSymbol type)
        {
            var containingTypes = new Stack<INamedTypeSymbol>();

            for (var t = type.ContainingType; t != null; t = t.ContainingType)
            {
                containingTypes.Push(t);
            }

            foreach (INamedTypeSymbol t in containingTypes)
            {
                source.Append("    public partial class ");
                source.Append(t.Name);
                source.AppendLine();
                source.AppendLine("    {");
            }
        }

        private static void AppendContainingTypesEnd(StringBuilder source, INamedTypeSymbol type)
        {
            for (var t = type.ContainingType; t != null; t = t.ContainingType)
            {
                source.AppendLine("    }");
            }
        }

        private static void AppendNamespaceStart(StringBuilder source, INamedTypeSymbol type)
        {
            string namespaceName = type.ContainingNamespace?.ToDisplayString();

            if (string.IsNullOrEmpty(namespaceName))
            {
                return;
            }

            source.Append("namespace ");
            source.Append(namespaceName);
            source.AppendLine();
            source.AppendLine("{");
        }

        private static void AppendNamespaceEnd(StringBuilder source, INamedTypeSymbol type)
        {
            string namespaceName = type.ContainingNamespace?.ToDisplayString();

            if (string.IsNullOrEmpty(namespaceName))
            {
                return;
            }

            source.AppendLine("}");
        }

        private static string GetHintName(INamedTypeSymbol type)
        {
            string name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            return name
                       .Replace("global::", string.Empty)
                       .Replace(".", "_")
                       .Replace("<", "_")
                       .Replace(">", "_")
                   + ".MonoBehaviourService.g.cs";
        }
    }
}