using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace OneLastClick.Services.SourceGenerator
{
    [Generator]
    public class PerAssemblyApplicationServiceRegisterSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            string compilationName = context.Compilation.AssemblyName ?? "<unknown>";

            if (OneLastClickServicesReferences.TryResolveReferences(context, out OneLastClickServicesReferences references) == false)
            {
                return;
            }
            
            List<INamedTypeSymbol> applicationServices = ContextExtensions.GetAllTypesWithAttribute(context, references.ApplicationServiceAttributeSymbol);

            if (applicationServices.Count == 0)
            {
                return;
            }
            
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDefinitions.ServicesFoundDiagnostic, Location.None, applicationServices.Count, compilationName));
            
            string builderTypeName = references.ServiceCollectionBuilderSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string applicationServicesTypeName = references.ApplicationServicesSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            DeterministicallySortServiceTypes(applicationServices);

            var source = new StringBuilder(
                $@"// <auto-generated />
using OneLastClick.Services.Attributes;

namespace OneLastClick.Services.Generated
{{
    public static partial class GeneratedApplicationServices
    {{
        [global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]
        private static void RegisterApplicationServices()
        {{ 
            {applicationServicesTypeName}.AddApplicationServicesBuilderFunction(RegisterGeneratedApplicationServices);
        }}

        public static void RegisterGeneratedApplicationServices( {builderTypeName} builder)
        {{
");

            foreach (INamedTypeSymbol service in applicationServices)
            {
                string serviceTypeName = service.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                source.Append("            builder.Register<");
                source.Append(serviceTypeName);
                source.AppendLine(">();");
            }

            source.Append(
                @"        }
    }
}
");

            context.AddSource("GeneratedApplicationServices.g.cs", source.ToString());
        }

        private static void DeterministicallySortServiceTypes(List<INamedTypeSymbol> serviceTypes)
        {
            serviceTypes.Sort((a, b) => string.CompareOrdinal(GetServiceSortName(a), GetServiceSortName(b)));
        }
        
        private static string GetServiceSortName(INamedTypeSymbol type)
        {
            return type.ContainingAssembly.Name + "." + type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }
    }
}